// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDaemonStatus() {
  return window['go']['main']['App']['GetDaemonStatus']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SpawnAgent(arg1, arg2) {
  return window['go']['main']['App']['SpawnAgent'](arg1, arg2);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}
