// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['AppService']['CreateTask'](arg1, arg2, arg3, arg4);
}

export function GetAgents() {
  return window['go']['main']['AppService']['GetAgents']();
}

export function GetChatHistory(arg1, arg2) {
  return window['go']['main']['AppService']['GetChatHistory'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['AppService']['GetConfig']();
}

export function GetDaemonStatus() {
  return window['go']['main']['AppService']['GetDaemonStatus']();
}

export function GetMessages(arg1) {
  return window['go']['main']['AppService']['GetMessages'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main']['AppService']['GetTasks'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['AppService']['SaveConfig'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['AppService']['SendMessage'](arg1, arg2, arg3);
}

export function SpawnAgent(arg1, arg2) {
  return window['go']['main']['AppService']['SpawnAgent'](arg1, arg2);
}

export function StopAgent(arg1) {
  return window['go']['main']['AppService']['StopAgent'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['main']['AppService']['Subscribe'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['AppService']['Unsubscribe'](arg1);
}
