// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the main service for the RAPID desktop app (Wails v3)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveRequest approves a pending approval request
 * @param {string} requestID
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function ApproveRequest(requestID, reason) {
    return $Call.ByID(52271404, requestID, reason);
}

/**
 * CallTool is a generic method to call any MCP tool through the Go backend
 * This avoids CORS issues when the frontend is running in a WebView
 * @param {string} toolName
 * @param {{ [_: string]: any }} $arguments
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function CallTool(toolName, $arguments) {
    return $Call.ByID(1942536424, toolName, $arguments).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateTask creates a new task
 * @param {string} title
 * @param {string} description
 * @param {string} priority
 * @param {string[]} tags
 * @returns {$CancellablePromise<$models.Task | null>}
 */
export function CreateTask(title, description, priority, tags) {
    return $Call.ByID(2570689667, title, description, priority, tags).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * FetchApprovals retrieves pending approvals
 * @param {string} status
 * @param {string} agentID
 * @param {number} limit
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function FetchApprovals(status, agentID, limit) {
    return $Call.ByID(469292770, status, agentID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetAgentLogs retrieves logs for a specific agent
 * @param {string} agentID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.LogEntry[]>}
 */
export function GetAgentLogs(agentID, limit) {
    return $Call.ByID(24727680, agentID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAgents returns list of active agents
 * @returns {$CancellablePromise<$models.Agent[]>}
 */
export function GetAgents() {
    return $Call.ByID(927907232).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetChatHistory retrieves chat history with a specific agent or all messages
 * @param {string} agentID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.Message[]>}
 */
export function GetChatHistory(agentID, limit) {
    return $Call.ByID(2221803232, agentID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetConfig returns the current rapid.json configuration
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetConfig() {
    return $Call.ByID(3902498144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetDaemonStatus returns the daemon's current status
 * @returns {$CancellablePromise<$models.DaemonStatus | null>}
 */
export function GetDaemonStatus() {
    return $Call.ByID(3378176028).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetLogsDirectory retrieves list of available log files
 * @returns {$CancellablePromise<string[]>}
 */
export function GetLogsDirectory() {
    return $Call.ByID(1176524048).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetMessages returns recent event bus messages
 * @param {number} limit
 * @returns {$CancellablePromise<$models.Message[]>}
 */
export function GetMessages(limit) {
    return $Call.ByID(1809247778, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetTasks returns list of tasks
 * @param {string} status
 * @returns {$CancellablePromise<$models.Task[]>}
 */
export function GetTasks(status) {
    return $Call.ByID(3756889144, status).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * OverrideSuggestion allows orchestrator to override a suggestion decision
 * @param {string} suggestionID
 * @param {string} decision
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function OverrideSuggestion(suggestionID, decision, reason) {
    return $Call.ByID(1997392622, suggestionID, decision, reason);
}

/**
 * RejectRequest rejects a pending approval request
 * @param {string} requestID
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function RejectRequest(requestID, reason) {
    return $Call.ByID(1904052038, requestID, reason);
}

/**
 * SaveConfig saves the rapid.json configuration
 * @param {{ [_: string]: any }} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(2775748437, config);
}

/**
 * SendMessage sends a message to an agent or broadcasts to all agents
 * @param {string} targetAgent
 * @param {string} messageType
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SendMessage(targetAgent, messageType, content) {
    return $Call.ByID(4154529951, targetAgent, messageType, content);
}

/**
 * SpawnAgent spawns a new agent with a persona
 * @param {string} persona
 * @param {string} worktree
 * @returns {$CancellablePromise<void>}
 */
export function SpawnAgent(persona, worktree) {
    return $Call.ByID(606885194, persona, worktree);
}

/**
 * StopAgent stops a running agent
 * @param {string} agentID
 * @returns {$CancellablePromise<void>}
 */
export function StopAgent(agentID) {
    return $Call.ByID(1641704647, agentID);
}

/**
 * SubmitVote submits a vote on a suggestion
 * @param {string} suggestionID
 * @param {string} vote
 * @returns {$CancellablePromise<void>}
 */
export function SubmitVote(suggestionID, vote) {
    return $Call.ByID(1120279030, suggestionID, vote);
}

/**
 * Subscribe creates a WebSocket subscription for real-time updates
 * Returns a subscription ID that can be used to unsubscribe
 * @param {string} eventType
 * @returns {$CancellablePromise<string>}
 */
export function Subscribe(eventType) {
    return $Call.ByID(2185949350, eventType);
}

/**
 * Unsubscribe removes a WebSocket subscription
 * @param {string} subID
 * @returns {$CancellablePromise<void>}
 */
export function Unsubscribe(subID) {
    return $Call.ByID(3278191231, subID);
}

/**
 * UpdateTaskStatus updates a task's status via MCP
 * @param {string} taskID
 * @param {string} status
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTaskStatus(taskID, status) {
    return $Call.ByID(679571916, taskID, status);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.Task.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $models.LogEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Agent.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.Message.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.DaemonStatus.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = $Create.Array($$createType1);
