// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Agent represents an agent on the event bus
 */
export class Agent {
    /**
     * Creates a new Agent instance.
     * @param {Partial<Agent>} [$$source = {}] - The source object to create the Agent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["worktree"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["session"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Agent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Agent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Agent(/** @type {Partial<Agent>} */($$parsedSource));
    }
}

/**
 * DaemonStatus represents the daemon's status
 */
export class DaemonStatus {
    /**
     * Creates a new DaemonStatus instance.
     * @param {Partial<DaemonStatus>} [$$source = {}] - The source object to create the DaemonStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pid"] = undefined;
        }
        if (!("socketPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["socketPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["uptime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["sessions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DaemonStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DaemonStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DaemonStatus(/** @type {Partial<DaemonStatus>} */($$parsedSource));
    }
}

/**
 * LogEntry represents a single log entry from an agent
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agentId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * Message represents an event bus message
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("fromAgent" in $$source)) {
            /**
             * @member
             * @type {Agent}
             */
            this["fromAgent"] = (new Agent());
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("payload" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }}
             */
            this["payload"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fromAgent" in $$parsedSource) {
            $$parsedSource["fromAgent"] = $$createField2_0($$parsedSource["fromAgent"]);
        }
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField4_0($$parsedSource["payload"]);
        }
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * Task represents a task in the system
 */
export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["priority"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["assignedTo"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Agent.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($Create.Any);
