import { useEffect, useCallback } from 'react'
import { useAppStore } from '../stores/app'

// Wails runtime types - these will be generated by Wails
declare global {
  interface Window {
    go: {
      main: {
        App: {
          GetDaemonStatus: () => Promise<{
            running: boolean
            pid?: number
            socketPath: string
            version?: string
            uptime?: number
            sessions?: number
          }>
          GetAgents: () => Promise<Array<{
            id: string
            name: string
            worktree?: string
            session?: string
          }>>
          GetTasks: (status: string) => Promise<Array<{
            id: string
            title: string
            description?: string
            status: string
            priority: string
            assignedTo?: string
            createdAt: string
            updatedAt: string
            tags?: string[]
          }>>
          GetMessages: (limit: number) => Promise<Array<{
            id: string
            type: string
            fromAgent: { id: string; name: string }
            timestamp: string
            payload: Record<string, unknown>
          }>>
          CreateTask: (
            title: string,
            description: string,
            priority: string,
            tags: string[]
          ) => Promise<{ id: string }>
          SpawnAgent: (persona: string, worktree: string) => Promise<void>
          StopAgent: (agentId: string) => Promise<void>
          GetConfig: () => Promise<Record<string, unknown>>
        }
      }
    }
  }
}

// Check if running in Wails context
const isWailsEnv = () => typeof window !== 'undefined' && window.go?.main?.App

/**
 * Hook to interact with Wails Go backend
 */
export function useWails() {
  const {
    setDaemonStatus,
    setAgents,
    setTasks,
    setMessages,
    setError,
    setConnecting,
  } = useAppStore()

  // Fetch daemon status
  const fetchDaemonStatus = useCallback(async () => {
    if (!isWailsEnv()) {
      // Mock data for development
      setDaemonStatus({
        running: true,
        socketPath: '~/.rapid/rapid.sock',
        version: '0.1.0-dev',
        uptime: 3600,
        sessions: 3,
      })
      return
    }

    try {
      const status = await window.go.main.App.GetDaemonStatus()
      setDaemonStatus(status)
    } catch (err) {
      setError(`Failed to get daemon status: ${err}`)
    }
  }, [setDaemonStatus, setError])

  // Fetch agents
  const fetchAgents = useCallback(async () => {
    if (!isWailsEnv()) {
      // Mock data for development
      setAgents([
        { id: 'orchestrator-1', name: 'orchestrator', worktree: 'main' },
        { id: 'worker-1', name: 'worker', worktree: 'feat/auth' },
        { id: 'designer-1', name: 'designer', worktree: 'main' },
      ])
      return
    }

    try {
      const agents = await window.go.main.App.GetAgents()
      setAgents(agents)
    } catch (err) {
      setError(`Failed to get agents: ${err}`)
    }
  }, [setAgents, setError])

  // Fetch tasks
  const fetchTasks = useCallback(async (status = '') => {
    if (!isWailsEnv()) {
      // Mock data for development
      setTasks([
        {
          id: 'task-1',
          title: 'Implement authentication',
          status: 'in_progress',
          priority: 'high',
          assignedTo: 'worker-1',
          createdAt: new Date(Date.now() - 7200000).toISOString(),
          updatedAt: new Date(Date.now() - 1800000).toISOString(),
          tags: ['feature', 'auth'],
        },
        {
          id: 'task-2',
          title: 'Review PR #42',
          status: 'pending',
          priority: 'normal',
          createdAt: new Date(Date.now() - 3600000).toISOString(),
          updatedAt: new Date(Date.now() - 3600000).toISOString(),
          tags: ['review'],
        },
        {
          id: 'task-3',
          title: 'Fix build errors',
          status: 'completed',
          priority: 'urgent',
          assignedTo: 'worker-1',
          createdAt: new Date(Date.now() - 10800000).toISOString(),
          updatedAt: new Date(Date.now() - 3600000).toISOString(),
          tags: ['bug', 'ci'],
        },
      ])
      return
    }

    try {
      const tasks = await window.go.main.App.GetTasks(status)
      setTasks(tasks)
    } catch (err) {
      setError(`Failed to get tasks: ${err}`)
    }
  }, [setTasks, setError])

  // Fetch messages
  const fetchMessages = useCallback(async (limit = 20) => {
    if (!isWailsEnv()) {
      // Mock data for development
      setMessages([
        {
          id: 'msg-1',
          type: 'completion',
          fromAgent: { id: 'worker-1', name: 'worker' },
          timestamp: new Date(Date.now() - 300000).toISOString(),
          payload: {
            title: 'Task completed',
            content: 'Implemented user authentication module',
          },
        },
        {
          id: 'msg-2',
          type: 'discovery',
          fromAgent: { id: 'designer-1', name: 'designer' },
          timestamp: new Date(Date.now() - 600000).toISOString(),
          payload: {
            title: 'Found existing pattern',
            content: 'Discovered auth middleware in src/middleware/auth.ts',
          },
        },
        {
          id: 'msg-3',
          type: 'coordination',
          fromAgent: { id: 'orchestrator-1', name: 'orchestrator' },
          timestamp: new Date(Date.now() - 900000).toISOString(),
          payload: {
            title: 'Task assigned',
            content: 'Assigned auth implementation to worker-1',
          },
        },
      ])
      return
    }

    try {
      const messages = await window.go.main.App.GetMessages(limit)
      setMessages(messages)
    } catch (err) {
      setError(`Failed to get messages: ${err}`)
    }
  }, [setMessages, setError])

  // Create task
  const createTask = useCallback(async (
    title: string,
    description: string,
    priority: string,
    tags: string[]
  ) => {
    if (!isWailsEnv()) {
      console.log('Would create task:', { title, description, priority, tags })
      return { id: `task-${Date.now()}` }
    }

    try {
      const result = await window.go.main.App.CreateTask(title, description, priority, tags)
      await fetchTasks()
      return result
    } catch (err) {
      setError(`Failed to create task: ${err}`)
      throw err
    }
  }, [fetchTasks, setError])

  // Spawn agent
  const spawnAgent = useCallback(async (persona: string, worktree: string) => {
    if (!isWailsEnv()) {
      console.log('Would spawn agent:', { persona, worktree })
      return
    }

    try {
      await window.go.main.App.SpawnAgent(persona, worktree)
      await fetchAgents()
    } catch (err) {
      setError(`Failed to spawn agent: ${err}`)
      throw err
    }
  }, [fetchAgents, setError])

  // Stop agent
  const stopAgent = useCallback(async (agentId: string) => {
    if (!isWailsEnv()) {
      console.log('Would stop agent:', agentId)
      return
    }

    try {
      await window.go.main.App.StopAgent(agentId)
      await fetchAgents()
    } catch (err) {
      setError(`Failed to stop agent: ${err}`)
      throw err
    }
  }, [fetchAgents, setError])

  // Initialize data on mount
  const initialize = useCallback(async () => {
    setConnecting(true)
    try {
      await Promise.all([
        fetchDaemonStatus(),
        fetchAgents(),
        fetchTasks(),
        fetchMessages(),
      ])
    } finally {
      setConnecting(false)
    }
  }, [fetchDaemonStatus, fetchAgents, fetchTasks, fetchMessages, setConnecting])

  return {
    initialize,
    fetchDaemonStatus,
    fetchAgents,
    fetchTasks,
    fetchMessages,
    createTask,
    spawnAgent,
    stopAgent,
  }
}

/**
 * Hook to auto-refresh data periodically
 */
export function useDataPolling(intervalMs = 5000) {
  const { fetchAgents, fetchTasks, fetchMessages, fetchDaemonStatus } = useWails()

  useEffect(() => {
    const interval = setInterval(() => {
      fetchDaemonStatus()
      fetchAgents()
      fetchTasks()
      fetchMessages()
    }, intervalMs)

    return () => clearInterval(interval)
  }, [fetchAgents, fetchTasks, fetchMessages, fetchDaemonStatus, intervalMs])
}
